"""
Chronicle AI - Markdown Export Functions

Export diary entries to Markdown files for daily and weekly summaries.
"""

import os
from pathlib import Path
from datetime import date, timedelta
from typing import List, Optional

from .models import Entry
from .repository import get_repository


# Default exports directory (relative to current working directory)
EXPORTS_DIR = os.getenv("CHRONICLE_EXPORTS_DIR", "exports")


def get_exports_path() -> Path:
    """Get the base exports directory path, creating it if needed."""
    path = Path(EXPORTS_DIR)
    path.mkdir(parents=True, exist_ok=True)
    return path


def export_entry_to_markdown(entry: Entry, output_dir: Optional[str] = None) -> str:
    """
    Export a single entry to a Markdown file.
    
    Creates a file at exports/daily/YYYY-MM-DD.md with the entry content.
    
    Args:
        entry: The Entry object to export
        output_dir: Optional custom output directory
        
    Returns:
        Path to the created file
    """
    base_dir = Path(output_dir) if output_dir else get_exports_path()
    daily_dir = base_dir / "daily"
    daily_dir.mkdir(parents=True, exist_ok=True)
    
    filename = f"{entry.date}.md"
    filepath = daily_dir / filename
    
    # Build markdown content
    lines = []
    
    # Title
    title = entry.title or f"Entry from {entry.date}"
    lines.append(f"# {title}")
    lines.append("")
    
    # Date badge
    lines.append(f"**📅 Date:** {entry.date}")
    lines.append("")
    
    # Narrative section
    lines.append("## 📖 Narrative")
    lines.append("")
    narrative = entry.narrative_text or "_No narrative generated yet._"
    lines.append(narrative)
    lines.append("")
    
    # Raw text section (collapsible details)
    lines.append("---")
    lines.append("")
    lines.append("<details>")
    lines.append("<summary>📝 Original Entry</summary>")
    lines.append("")
    lines.append(entry.raw_text or "_No raw text._")
    lines.append("")
    lines.append("</details>")
    lines.append("")
    
    # Footer
    lines.append("---")
    lines.append("*Generated by Chronicle AI 🎬*")
    
    content = "\n".join(lines)
    
    filepath.write_text(content, encoding="utf-8")
    
    return str(filepath)


def export_daily(entry_date: str, output_dir: Optional[str] = None) -> Optional[str]:
    """
    Export entries for a specific date to Markdown.
    
    Args:
        entry_date: Date in ISO format (YYYY-MM-DD)
        output_dir: Optional custom output directory
        
    Returns:
        Path to created file, or None if no entries found
    """
    repo = get_repository()
    entries = repo.list_entries_between_dates(entry_date, entry_date)
    
    if not entries:
        return None
    
    # If multiple entries on same day, combine them
    if len(entries) == 1:
        return export_entry_to_markdown(entries[0], output_dir)
    
    # Combine multiple entries into one
    combined_raw = "\n\n---\n\n".join(e.raw_text for e in entries if e.raw_text)
    combined_narrative = "\n\n".join(e.narrative_text for e in entries if e.narrative_text)
    
    # Use first entry's title or generate combined title
    titles = [e.title for e in entries if e.title]
    combined_title = titles[0] if titles else f"Day of {entry_date}"
    
    combined_entry = Entry(
        date=entry_date,
        raw_text=combined_raw,
        narrative_text=combined_narrative or None,
        title=combined_title
    )
    
    return export_entry_to_markdown(combined_entry, output_dir)


def get_week_number(d: date) -> str:
    """Get week identifier string (YYYY-WW format)."""
    year, week, _ = d.isocalendar()
    return f"{year}-W{week:02d}"


def export_weekly(
    end_date: Optional[str] = None,
    output_dir: Optional[str] = None
) -> Optional[str]:
    """
    Export entries from the last 7 days to a weekly Markdown summary.
    
    Creates a file at exports/weekly/week-YYYY-WW.md with all entries.
    
    Args:
        end_date: End date for the week (default: today)
        output_dir: Optional custom output directory
        
    Returns:
        Path to created file, or None if no entries found
    """
    repo = get_repository()
    
    # Determine date range
    if end_date:
        end = date.fromisoformat(end_date)
    else:
        end = date.today()
    
    start = end - timedelta(days=6)
    
    # Get entries
    entries = repo.list_entries_between_dates(
        start.isoformat(),
        end.isoformat()
    )
    
    if not entries:
        return None
    
    # Sort entries by date ascending for chronological order
    entries.sort(key=lambda e: e.date)
    
    # Prepare output directory
    base_dir = Path(output_dir) if output_dir else get_exports_path()
    weekly_dir = base_dir / "weekly"
    weekly_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate filename
    week_id = get_week_number(end)
    filename = f"week-{week_id}.md"
    filepath = weekly_dir / filename
    
    # Build markdown content
    lines = []
    
    # Header
    lines.append(f"# 📺 Week {week_id}")
    lines.append("")
    lines.append(f"**Period:** {start.isoformat()} to {end.isoformat()}")
    lines.append("")
    lines.append(f"**Episodes:** {len(entries)}")
    lines.append("")
    lines.append("---")
    lines.append("")
    
    # Table of contents
    lines.append("## 📑 Episodes This Week")
    lines.append("")
    for entry in entries:
        title = entry.title or f"Entry from {entry.date}"
        anchor = entry.date.replace("-", "")
        lines.append(f"- [{entry.date}: {title}](#{anchor})")
    lines.append("")
    lines.append("---")
    lines.append("")
    
    # Each day's content
    for entry in entries:
        anchor = entry.date.replace("-", "")
        title = entry.title or f"Entry from {entry.date}"
        
        lines.append(f"<a id=\"{anchor}\"></a>")
        lines.append(f"## 🎬 {entry.date} – {title}")
        lines.append("")
        
        narrative = entry.narrative_text or "_No narrative generated._"
        lines.append(narrative)
        lines.append("")
        lines.append("---")
        lines.append("")
    
    # Footer
    lines.append("*Weekly summary generated by Chronicle AI 🎬*")
    
    content = "\n".join(lines)
    
    filepath.write_text(content, encoding="utf-8")
    
    return str(filepath)


def export_all_entries(output_dir: Optional[str] = None) -> List[str]:
    """
    Export all entries to individual daily Markdown files.
    
    Args:
        output_dir: Optional custom output directory
        
    Returns:
        List of paths to created files
    """
    repo = get_repository()
    entries = repo.list_entries()
    
    created_files = []
    for entry in entries:
        filepath = export_entry_to_markdown(entry, output_dir)
        created_files.append(filepath)
    
    return created_files
